<?php
$user = new \Core\Admin\User\User();
if (!$user->isLoggedIn()) exit('You are not logged in.');

// we have to import these variables
global $entity;
global $errors;

$isNew = (!$entity || !$entity->getId());
?>
<h2 class="page-title">
    <?php
    if ($isNew) {
        echo 'Create New ' . ucwords($_POST['type']);
    }else{
        echo 'Edit ' . ucwords($_POST['type']);
    }
    ?>
</h2>
<div class="admin-form-wrapper">
    <form action="" method="post" enctype="multipart/form-data">
<?php

if (!isset($errors)) $errors = [];

$form = new \Core\Helper\Form($entity, $errors);
// get entity type
$type = $_POST['type'];
switch ($type) {
    case 'event':
        echo $form->textInput('title', 'Event Name');
        echo $form->dateTimeInput('datetime', 'Date and Time');
        echo $form->textInput('location', 'Location');
        echo $form->textArea('content', 'Description');
        break;
    case 'page':
        echo $form->textInput('title', 'Page Title');
        echo $form->textInput('url_key', 'URL Key');
        echo $form->textArea('content', 'Page Content');
        echo $form->yesNoInput('is_active', 'Enabled');
        echo $form->yesNoInput('show_in_menu', 'Create Menu Link');
        echo $form->textInput('sort_order', 'Sort Order', '1');
        break;
    case 'photo':
        echo $form->textInput('title', 'Image title');
        echo $form->imageInput('image', 'Select Image File');
        echo $form->yesNoInput('is_active', 'Enabled');
        echo $form->textInput('sort_order', 'Sort Order', '1');
        break;
}
?>
        <?php if (isset($_POST['id'])): ?>
        <input type="hidden" name="id" value="<?php echo $_POST['id'] ?>"/>
        <?php endif; ?>
        <input type="hidden" name="type" value="<?php echo $_POST['type']?>">
        <input type="hidden" name="action" value="save"/>
        <input type="submit" value="Save" />
    </form>
    <form action="" method="post">
        <input type="submit" value="Back" />
    </form>
</div>
<?php $jsFile = 'http://' . BASE_URL . 'web/js/edit.js' ?>
<script type="application/javascript" src="<?php echo $jsFile ?>"></script>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        width : 800,
        height : 400,
        browser_spellcheck : true,

        plugins: "textcolor,paste,searchreplace,fullscreen,hr,link,anchor,image,charmap,media,autoresize,autosave,contextmenu,wordcount",

        toolbar1: "cut,copy,paste,|,undo,redo,removeformat,|hr,|,link,unlink,anchor,image,|,charmap,media,|,search,replace,|,fullscreen",
        toolbar2:	"bold,italic,underline,strikethrough,forecolor,backcolor,|,alignleft,aligncenter,alignright,alignjustify,|,formatselect,|,bullist,numlist,|,outdent,indent,blockquote,"
    });
</script>