<?php $photos = \Core\DB\DB::getConnection()->getPhotos() ?>
<?php if (!empty($photos)): ?>
<div class="photo-gallery">
    <?php foreach ($photos as $photo): ?>
        <div class="photo-thumb-wrapper">
            <?php echo $photo->toThumbnailHtml() ?>
            <input type="hidden" value="<?php $photo->getImage() ?>" />
        </div>
    <?php endforeach; ?>
</div>
<?php else: ?>
<h3>No photos at this time.</h3>
<?php endif; ?>
